codecov:
  require_ci_to_pass: yes # Tell Codecov to not create its statuses until CI has finished running
  notify:
    after_n_builds: 12
    wait_for_ci: yes # Tell Codecov to not create its statuses until CI has finished running

coverage:
  status:
    project:
      default:
        target: auto
      minimum:
        target: "100%"
