codecov:
  notify:
    # Tell Codecov to not create its statuses until CI has finished running
    wait_for_ci: yes
coverage:
  status:
    project:
      default:
        target: auto
      minimum:
        target: "100%"
