name: CI
on:
  merge_group: # GitHub Merge Queue
  pull_request:
  push:
    branches:
      - main
    tags: '*'
concurrency:
  # Skip intermediate builds: all builds except for builds on the `main` branch
  # Cancel intermediate builds: only pull request builds
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.ref != 'refs/heads/main' || github.run_number }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
permissions:
  contents: read
jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.0' # TODO: delete some of these
          - '1.1' # TODO: delete some of these
          - '1.2' # TODO: delete some of these
          - '1.3' # TODO: delete some of these
          - '1.4' # TODO: delete some of these
          - '1.5' # TODO: delete some of these
          - '1.6' # TODO: delete some of these
          - '1.7' # TODO: delete some of these
          - '1.8' # TODO: delete some of these
          - '1.9' # TODO: delete some of these
          - '1'
          - 'nightly'
        os:
          - ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
        with:
          persist-credentials: false
      - uses: julia-actions/setup-julia@f40c4b69330df1d22e7590c12e76dc2f9c66e0bc
        with:
          version: '${{ matrix.version }}'
      - uses: julia-actions/julia-buildpkg@5484b0e27fa12452eb1deffe4fd40ff700c429b9
      - uses: julia-actions/julia-runtest@79a7e100883947123f8263c5f06e6c0ea3eb972f
        with:
          coverage: true
      - uses: julia-actions/julia-processcoverage@03114f09f119417c3242a9fb6e0b722676aedf38
      - uses: codecov/codecov-action@v3
        with:
          verbose: true
          fail_ci_if_error: true
          files: lcov.info
